### ISSUE TITLE
请问，使用该docker部署时候，自动获取的是最新ss-libev的稳定版么？

### ISSUE THREAD

**Issue by CookieJaySJ** [primovist/shadowsocks-libev.simple-obfs.v2ray-plugin#1]

**Comment by primovist** [comment]
> *No description provided.*

我尽量保持最新。肯定是稳定版。版本内容在Dockerfile内可以看到。

**Comment by CookieJaySJ** [comment]
> > _No description provided._
> 
> 我尽量保持最新。是git当前版本制作。
好的 谢谢
